apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mutating-webhook.fullname" . }}-config
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
data:
  podSelectorLabels.json: |
    {{- toJson .Values.webhook.podSelectorLabels | nindent 4 }}
  labels.json: |
    {{- toJson .Values.webhook.labels | nindent 4 }}
  nodeSelectorLabels.json: |
    {{- toJson .Values.webhook.nodeSelectorLabels | nindent 4 }}

