apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mutating-webhook.fullname" . }}-config
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
data:
  labels.json: |
    {{- toJson .Values.webhook.labels | nindent 4 }}
  topologySpreadConstraints.json: |
    {{- toJson .Values.webhook.topologySpreadConstraints | nindent 4 }}

