apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"

  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
webhooks:
- name: {{ include "mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  clientConfig:
    service:
      name: {{ include "mutating-webhook.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  {{- with .Values.webhook.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
