apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "mutating-webhook.selectorLabels" . | nindent 4 }}
